### ISSUE TITLE
please add installation instructions for x2go and cyberduck

### ISSUE THREAD

**Issue by ccraddock** [Brainhack-AMX/Brainhacking-101#1]
so that attendees can attach to the CPAC AMI and browse data on the fcp-indi bucket.

**Comment by ccraddock** [comment]
please also indicate what can and cannot be installed on windows, and add the comments:
- users who have trouble with the installation can get help at the brainhacking 101 installfests
- users who do not want to install the software, or only have access to windows, can follow along with the demos using amazon web services could computing. These users will need to install x2go.

**Comment by jpellman** [comment]
I can't find a Cyberduck binary for Linux.  The other packages look to be available on Windows.

**Comment by ccraddock** [comment]
Ok. Is there an alternative for linux?

**Comment by jpellman** [comment]
There's a Java program for browsing S3 buckets.  I've added install instructions for it.
